touch_scroll_multiplier 10.0
background_opacity 0.8

font_family      SF Mono
bold_font        SF Mono Bold
italic_font      SF Mono Regular Italic
bold_italic_font SF Mono Bold Italic
font_size        11.0

map ctrl+plus    change_font_size all +0.5
map ctrl+equal   change_font_size all +0.5
map ctrl+minus   change_font_size all -0.5
map ctrl+0       change_font_size all 0
