general {
    lock_cmd = pidof hyprlock || ~/.config/hypr/lock.sh
    before_sleep_cmd = pidof hyprlock || ~/.config/hypr/lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on; pidof hyprlock >/dev/null || (~/.config/hypr/lock.sh &); ~/.config/hypr/after-wake.sh &
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}
